# Generated by Django 3.2.15 on 2022-09-20 15:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0003_delete_nonstorage_packages"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plan",
            name="user_type",
            field=models.PositiveSmallIntegerField(
                choices=[(1, "Person"), (2, "Organization"), (3, "Team")], default=1
            ),
        ),
        migrations.DeleteModel(
            name="ExtraPackageTypeJobMinutes",
        ),
        migrations.DeleteModel(
            name="ExtraPackageTypeStorage",
        ),
        migrations.AddField(
            model_name="extrapackagetype",
            name="max_quantity",
            field=models.PositiveIntegerField(default=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="extrapackagetype",
            name="min_quantity",
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="extrapackagetype",
            name="type",
            field=models.CharField(
                choices=[("storage", "Storage")],
                default="storage",
                max_length=100,
                unique=True,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="extrapackagetype",
            name="unit_amount",
            field=models.PositiveIntegerField(default=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="extrapackagetype",
            name="unit_label",
            field=models.CharField(max_length=100, blank=True, null=True, default="MB"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="extrapackage",
            name="quantity",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
