# Generated by Django 3.2.15 on 2022-09-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0004_auto_20220920_1732"),
    ]

    operations = [
        migrations.AlterField(
            model_name="extrapackage",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="plan",
            name="is_trial",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="plan",
            name="max_trial_organizations",
            field=models.IntegerField(
                default=1,
                help_text="Maximum number of trial organizations that the user can create. Set -1 to allow unlimited trial organizations.",
            ),
        ),
    ]
