# Generated by Django 3.2.15 on 2022-10-20 01:40

import django.db.models.deletion
from django.db import migrations, models


def add_extra_packages_to_subscriptions(apps, schema_editor):
    Subscription = apps.get_model("subscription", "Subscription")
    ExtraPackage = apps.get_model("subscription", "ExtraPackage")

    for package in ExtraPackage.objects.all():
        subscription = (
            Subscription.objects.filter(
                account=package.account,
                active_since__lte=package.active_since,
            )
            .order_by("active_since")
            .first()
        )
        package.subscription = subscription
        package.save()


def add_extra_packages_to_accounts(apps, schema_editor):
    ExtraPackage = apps.get_model("subscription", "ExtraPackage")

    for package in ExtraPackage.objects.all():
        package.account = package.subscription.account
        package.save()


class Migration(migrations.Migration):

    dependencies = [
        ("subscription", "0005_auto_20220923_1602"),
    ]

    operations = [
        migrations.RenameField(
            model_name="extrapackage",
            old_name="start_date",
            new_name="active_since",
        ),
        migrations.RenameField(
            model_name="extrapackage",
            old_name="end_date",
            new_name="active_until",
        ),
        migrations.AlterField(
            model_name="extrapackage",
            name="active_since",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="extrapackage",
            name="active_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="extrapackage",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="subscription.subscription",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="extrapackage",
            name="account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extra_packages",
                to="core.useraccount",
                null=True,
            ),
        ),
        migrations.SeparateDatabaseAndState(
            database_operations=[
                # put your sql, python, whatever data migrations here
            ],
            state_operations=[
                # field/model changes goes here
            ],
        ),
        # NOTE avoids `django.db.utils.OperationalError: cannot CREATE INDEX "subscription_extrapackage" because it has pending trigger events`
        # I failed to solve the issue by using `SeparateDatabaseAndState`.
        migrations.RunSQL(
            "SET CONSTRAINTS ALL IMMEDIATE", reverse_sql=migrations.RunSQL.noop
        ),
        migrations.RunPython(
            add_extra_packages_to_subscriptions, add_extra_packages_to_accounts
        ),
        migrations.RunSQL(
            migrations.RunSQL.noop,
            reverse_sql="SET CONSTRAINTS ALL IMMEDIATE",
        ),
        migrations.RemoveField(
            model_name="extrapackage",
            name="account",
        ),
        migrations.AlterField(
            model_name="extrapackage",
            name="subscription",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="packages",
                to="subscription.subscription",
                null=False,
            ),
        ),
    ]
