# Generated by Django 3.2.15 on 2022-10-13 13:25

import django.db.models.deletion
from django.db import migrations, models
from django.db.models import Q
from django.utils import timezone


def set_active_plan(apps, schema_editor):
    UserAccount = apps.get_model("core", "UserAccount")
    Subscription = apps.get_model("subscription", "Subscription")
    Plan = apps.get_model("subscription", "Plan")

    for account in UserAccount.objects.all():
        subscription = (
            Subscription.objects.filter(
                Q(active_until__isnull=True) | Q(active_until__gt=timezone.now())
            )
            .filter(status__startswith="active_")
            .first()
        )

        if subscription:
            plan_id = subscription.plan_id
        else:
            plan = Plan.objects.filter(
                is_default=True, user_type=account.user.type
            ).first()
            plan_id = plan.id

        account.plan_id = plan_id
        account.save(update_fields=["plan_id"])


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0058_auto_20220914_2049"),
        ("subscription", "0005_auto_20220923_1602"),
    ]

    operations = [
        migrations.AlterField(
            model_name="useraccount",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="subscription.plan",
                null=True,
            ),
        ),
        migrations.RunPython(migrations.RunPython.noop, set_active_plan),
        migrations.RemoveField(
            model_name="useraccount",
            name="plan",
        ),
    ]
